services:
  - type: web
    name: telegram-movie-bot-render
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 --bind 0.0.0.0:10000 render_bot:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: HF_API_URL
        value: https://mandyg8-telegram-movie-bot.hf.space
      - key: RENDER_EXTERNAL_HOSTNAME
        value: telegram-test-bot-2-impw.onrender.com